//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BasicInformationOfVideoSurveillance
{
    public string id { get; set; }
    public string BIOVSDeviceName { get; set; }
    public string BIOVSIP协议 { get; set; }
    public string BIOVSPort { get; set; }
    public string BIOVSGetuserrolelist { get; set; }
    public string BIOVSCode { get; set; }
    public string BIOVSWhetherThePasswordIsCipherOrNot { get; set; }
    public string BIOVSAffiliatedArea { get; set; }
    public string BIOVSPersonalNumber { get; set; }
    public string BIOVSEquipmentType { get; set; }
    public string BIOVSRegistrationType { get; set; }
    public string BIOVSSerialNumber { get; set; }
    public string BIOVS { get; set; }
    public string BIOVSDomain { get; set; }
    public string BIOVSAlarmInput { get; set; }
    public string BIOVSAlarmOutput { get; set; }
    public string BIOVSIntercomChannel { get; set; }
    public string BIOVSAnalogChannelNumber { get; set; }
    public string BIOVSNumberChannel { get; set; }
    public string BIOVSFirstRoad1 { get; set; }
    public string BIOVSSecondRoad2 { get; set; }
    public string BIOVSThirdRoad3 { get; set; }
    public string BIOVSFourthRoad4 { get; set; }
    public string BIOVSFifthRoad5 { get; set; }
    public string BIOVSSixthRoad6 { get; set; }
    public string BIOVSSeventhRoad7 { get; set; }
    public string BIOVSEighthRoad8 { get; set; }
    public string BIOVSNinthRoad9 { get; set; }
    public string BIOVSTenthRoad10 { get; set; }
    public string BIOVSEleventhRoad11 { get; set; }
    public string BIOVSTwelfthRoad12 { get; set; }
    public string BIOVSThirteenthRoad13 { get; set; }
    public string BIOVSFourteenthRoad14 { get; set; }
    public string BIOVSFifteenthRoad15 { get; set; }
    public string BIOVSSixteenthRoad16 { get; set; }
    public string BIOVSSeventeenthRoad17 { get; set; }
    public string BIOVSEighteenthRoad18 { get; set; }
    public string BIOVSNineteenthRoad19 { get; set; }
    public string BIOVSTwentiethRoad20 { get; set; }
    public string BIOVSTwentyFirstRoad21 { get; set; }
    public string BIOVSTwentySecondRoad22 { get; set; }
    public string BIOVSTwentyThirdRoad23 { get; set; }
    public string BIOVSTwentyFourthRoad24 { get; set; }
    public string BIOVSTwentyFifthRoad25 { get; set; }
    public string BIOVSTwentySixthRoad26 { get; set; }
    public string BIOVSTwentySeventhRoad27 { get; set; }
    public string BIOVSTwentyEighthRoad28 { get; set; }
    public string BIOVSTwentyNinthRoad29 { get; set; }
    public string BIOVSThirtiethRoad30 { get; set; }
    public string BIOVSThirtyFirstRoad31 { get; set; }
    public string BIOVSThirtySecondRoad32 { get; set; }
    public string BIOVSDigitalFirst1 { get; set; }
    public string BIOVSDigitalSecond2 { get; set; }
    public string BIOVSDigitalThird3 { get; set; }
    public string BIOVSDigitalFourth4 { get; set; }
    public string BIOVSDigitalFifth5 { get; set; }
    public string BIOVSDigitalSixth6 { get; set; }
    public string BIOVSDigitalSeventh7 { get; set; }
    public string BIOVSDigitalEighth8 { get; set; }
    public string BIOVSDigitalNinth9 { get; set; }
    public string BIOVSDigitalTenth10 { get; set; }
    public string BIOVSDigitalEleventh11 { get; set; }
    public string BIOVSDigitalTwelfth12 { get; set; }
    public string BIOVSDigitalThirteenth13 { get; set; }
    public string BIOVSDigitalFourteenth14 { get; set; }
    public string BIOVSDigitalFifteenth15 { get; set; }
    public string BIOVSDigitalSixteenth16 { get; set; }
    public string BIOVSDigitalSeventeenth17 { get; set; }
    public string BIOVSDigitalEighteenth18 { get; set; }
    public string BIOVSDigitalNineteenth19 { get; set; }
    public string BIOVSDigitalTwentieth20 { get; set; }
    public string BIOVSDigitalTwentyFirst21 { get; set; }
    public string BIOVSDigitalTwentySecond22 { get; set; }
    public string BIOVSDigitalTwentyThird23 { get; set; }
    public string BIOVSDigitalTwentyFourth24 { get; set; }
    public string BIOVSDigitalTwentyFifth25 { get; set; }
    public string BIOVSDigitalTwentySixth26 { get; set; }
    public string BIOVSDigitalTwentySeventh27 { get; set; }
    public string BIOVSDigitalTwentyEighth28 { get; set; }
    public string BIOVSDigitalTwentyNinth29 { get; set; }
    public string BIOVSDigitalThirtieth30 { get; set; }
    public string BIOVSDigitalThirtyFirst31 { get; set; }
    public string BIOVSDigitalThirtySecond32 { get; set; }
    public Nullable<int> VersionNo { get; set; }
    public string TransactionID { get; set; }
    public string CreateBy { get; set; }
    public Nullable<System.DateTime> CreateOn { get; set; }
    public string UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateOn { get; set; }
    public string DataLevel { get; set; }
    public string Latitude { get; set; }
    public string Longitude { get; set; }
    public Nullable<int> IsDeleted { get; set; }
    public string Polyline { get; set; }
    public string Polygon { get; set; }
    public string BIOVSAddress { get; set; }
    public Nullable<int> ord { get; set; }
}
