//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BasicPopulation
{
    public string id { get; set; }
    public string BPName { get; set; }
    public string BPHeadPortrait { get; set; }
    public string BPIdCard { get; set; }
    public string BPDomicilePlace { get; set; }
    public string BPPlaceOfResidence { get; set; }
    public string BPUnitNumber { get; set; }
    public string BPDoorNumber { get; set; }
    public string BPCommonModeOfContact { get; set; }
    public string BPDirectKinship { get; set; }
    public string BPDeathCertificate { get; set; }
    public string BPPhoto { get; set; }
    public Nullable<int> VersionNo { get; set; }
    public string TransactionID { get; set; }
    public string CreateBy { get; set; }
    public Nullable<System.DateTime> CreateOn { get; set; }
    public string UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateOn { get; set; }
    public string DataLevel { get; set; }
    public string Latitude { get; set; }
    public string Longitude { get; set; }
    public Nullable<int> IsDeleted { get; set; }
    public Nullable<int> ord { get; set; }
    public string Polyline { get; set; }
    public string Polygon { get; set; }
}
