//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Building
{
    public string id { get; set; }
    public string BName { get; set; }
    public string BAddress { get; set; }
    public string BBuildingNumber { get; set; }
    public string BUnitNumber { get; set; }
    public string BDoorNumber { get; set; }
    public string BTheNameOfEnterprise { get; set; }
    public string BSuperinrtendent { get; set; }
    public string BContactModeOfThePersonInCharge { get; set; }
    public string BExtent { get; set; }
    public string BRemarks { get; set; }
    public Nullable<int> VersionNo { get; set; }
    public string TransactionID { get; set; }
    public string CreateBy { get; set; }
    public Nullable<System.DateTime> CreateOn { get; set; }
    public string UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateOn { get; set; }
    public string DataLevel { get; set; }
    public string Latitude { get; set; }
    public string Longitude { get; set; }
    public Nullable<int> IsDeleted { get; set; }
    public Nullable<int> ord { get; set; }
    public string Polyline { get; set; }
    public string Polygon { get; set; }
    public string BIndustrialParkName { get; set; }
    public string BSerialNumber { get; set; }
    public string BTenant { get; set; }
    public string BStartAndStop { get; set; }
    public Nullable<float> BRentingArea { get; set; }
    public string BDeposit { get; set; }
    public string BUnitPrice { get; set; }
    public string BMonthlyRent { get; set; }
    public string BAnnualRent { get; set; }
    public string BPropertyOfRentingUnits { get; set; }
    public string BEnvironmentalProtectionFormalities { get; set; }
    public Nullable<float> BBuiltUpArea { get; set; }
    public Nullable<System.DateTime> BStartTime { get; set; }
    public Nullable<System.DateTime> BEndTime { get; set; }
    public string BContacts { get; set; }
    public string BContactNumber { get; set; }
    public string BApprovalDocument { get; set; }
}
