//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BusinessManagement
{
    public string id { get; set; }
    public string BMEnterpriseName { get; set; }
    public string BMLegalPerson { get; set; }
    public string BMSuperinrtendent { get; set; }
    public string BMContactModeOfThePersonInCharge { get; set; }
    public string BMCompanyPosition { get; set; }
    public Nullable<System.DateTime> BMDateOfAdmission { get; set; }
    public Nullable<int> VersionNo { get; set; }
    public string TransactionID { get; set; }
    public string CreateBy { get; set; }
    public Nullable<System.DateTime> CreateOn { get; set; }
    public string UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateOn { get; set; }
    public string DataLevel { get; set; }
    public string Latitude { get; set; }
    public string Longitude { get; set; }
    public Nullable<int> IsDeleted { get; set; }
    public string BMBusinessType { get; set; }
    public string BMServiceType { get; set; }
    public string BMApplicant { get; set; }
    public string BMIdNumber { get; set; }
    public string BMChairperson { get; set; }
    public Nullable<System.DateTime> BMHallAcceptanceTime { get; set; }
    public string BMAgent { get; set; }
    public Nullable<System.DateTime> BMCreationTime { get; set; }
    public string BMBackwardness { get; set; }
    public Nullable<int> ord { get; set; }
    public string Polyline { get; set; }
    public string Polygon { get; set; }
}
