//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class EmploymentAssistance
{
    public string id { get; set; }
    public string EAPersonalNumber { get; set; }
    public string EAName { get; set; }
    public string EAIdCard { get; set; }
    public string EAChairperson { get; set; }
    public string EACivilization { get; set; }
    public Nullable<int> EAAge { get; set; }
    public string EADegreeOfEducation { get; set; }
    public string EANatureOfHouseholdRegistration { get; set; }
    public string EAWhetherOrNotDisability { get; set; }
    public string EATrainingWill { get; set; }
    public string EACommonModeOfContact { get; set; }
    public string EATypeOfPersonnel { get; set; }
    public string EAFormOfEmployment { get; set; }
    public string EAContent1 { get; set; }
    public string EAContent2 { get; set; }
    public string EAContent3 { get; set; }
    public string EAContent4 { get; set; }
    public Nullable<int> VersionNo { get; set; }
    public string TransactionID { get; set; }
    public string CreateBy { get; set; }
    public Nullable<System.DateTime> CreateOn { get; set; }
    public string UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateOn { get; set; }
    public string DataLevel { get; set; }
    public string Latitude { get; set; }
    public string Longitude { get; set; }
    public Nullable<int> IsDeleted { get; set; }
    public string Polyline { get; set; }
    public string Polygon { get; set; }
    public Nullable<int> ord { get; set; }
}
