//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class Model1Container : DbContext
{
    public Model1Container()
        : base("name=Model1Container")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Access> Access { get; set; }
    public virtual DbSet<AccessRecord> AccessRecord { get; set; }
    public virtual DbSet<AccuratePovertyAlleviationManagement> AccuratePovertyAlleviationManagement { get; set; }
    public virtual DbSet<ActiveInspection> ActiveInspection { get; set; }
    public virtual DbSet<ActivityInformation> ActivityInformation { get; set; }
    public virtual DbSet<Advise> Advise { get; set; }
    public virtual DbSet<AgroTechnicalPersonnelManagement> AgroTechnicalPersonnelManagement { get; set; }
    public virtual DbSet<aGuideToTheConvenienceOfPeople> aGuideToTheConvenienceOfPeople { get; set; }
    public virtual DbSet<AirDetection> AirDetection { get; set; }
    public virtual DbSet<BasicInformationOfVideoSurveillance> BasicInformationOfVideoSurveillance { get; set; }
    public virtual DbSet<BasicPopulation> BasicPopulation { get; set; }
    public virtual DbSet<BonusRecord> BonusRecord { get; set; }
    public virtual DbSet<Building> Building { get; set; }
    public virtual DbSet<Businesslike> Businesslike { get; set; }
    public virtual DbSet<BusinessManagement> BusinessManagement { get; set; }
    public virtual DbSet<BusinessRegistration> BusinessRegistration { get; set; }
    public virtual DbSet<BusinessReservation> BusinessReservation { get; set; }
    public virtual DbSet<BusinessTracking> BusinessTracking { get; set; }
    public virtual DbSet<Cadre> Cadre { get; set; }
    public virtual DbSet<CameraManagement> CameraManagement { get; set; }
    public virtual DbSet<CampusAndSurroundingSecurity> CampusAndSurroundingSecurity { get; set; }
    public virtual DbSet<CampusPropaganda> CampusPropaganda { get; set; }
    public virtual DbSet<ChildrensMedicalInsuranceRegistration> ChildrensMedicalInsuranceRegistration { get; set; }
    public virtual DbSet<Conference> Conference { get; set; }
    public virtual DbSet<ConferenceNotice> ConferenceNotice { get; set; }
    public virtual DbSet<ConflictManagement> ConflictManagement { get; set; }
    public virtual DbSet<ConsolationRecord> ConsolationRecord { get; set; }
    public virtual DbSet<ContractManagement> ContractManagement { get; set; }
    public virtual DbSet<ControlOfPriorityPopulation> ControlOfPriorityPopulation { get; set; }
    public virtual DbSet<CustomButton> CustomButton { get; set; }
    public virtual DbSet<DepartmentManagement> DepartmentManagement { get; set; }
    public virtual DbSet<DocumentManagement> DocumentManagement { get; set; }
    public virtual DbSet<EfficiencyStatistics> EfficiencyStatistics { get; set; }
    public virtual DbSet<EmploymentAssistance> EmploymentAssistance { get; set; }
    public virtual DbSet<Engineer> Engineer { get; set; }
    public virtual DbSet<EngineeringManagement> EngineeringManagement { get; set; }
    public virtual DbSet<EngineeringProblems> EngineeringProblems { get; set; }
    public virtual DbSet<EngineeringTaskManagement> EngineeringTaskManagement { get; set; }
    public virtual DbSet<Enterprise> Enterprise { get; set; }
    public virtual DbSet<EnterpriseInformationRegistration> EnterpriseInformationRegistration { get; set; }
    public virtual DbSet<ExpertManagement> ExpertManagement { get; set; }
    public virtual DbSet<Family> Family { get; set; }
    public virtual DbSet<FamilyFarmManagement> FamilyFarmManagement { get; set; }
    public virtual DbSet<FeaturesOfXiangxi> FeaturesOfXiangxi { get; set; }
    public virtual DbSet<FileManagement> FileManagement { get; set; }
    public virtual DbSet<FinancialManagement> FinancialManagement { get; set; }
    public virtual DbSet<Framework> Framework { get; set; }
    public virtual DbSet<GridEvent> GridEvent { get; set; }
    public virtual DbSet<GridEventManagement> GridEventManagement { get; set; }
    public virtual DbSet<GridManagement> GridManagement { get; set; }
    public virtual DbSet<GridPersonnelManagement> GridPersonnelManagement { get; set; }
    public virtual DbSet<GuideToAffairs> GuideToAffairs { get; set; }
    public virtual DbSet<GuideToPartyAffairs> GuideToPartyAffairs { get; set; }
    public virtual DbSet<HouseProperty> HouseProperty { get; set; }
    public virtual DbSet<HumanFlowMonitoring> HumanFlowMonitoring { get; set; }
    public virtual DbSet<IndustrialParkBuilding> IndustrialParkBuilding { get; set; }
    public virtual DbSet<Information> Information { get; set; }
    public virtual DbSet<InformationManagementOfPartyMembers> InformationManagementOfPartyMembers { get; set; }
    public virtual DbSet<Investors> Investors { get; set; }
    public virtual DbSet<LatestNews> LatestNews { get; set; }
    public virtual DbSet<ListManagementOfThematicResponsibility> ListManagementOfThematicResponsibility { get; set; }
    public virtual DbSet<ListOfResponsibilities> ListOfResponsibilities { get; set; }
    public virtual DbSet<LogonLog> LogonLog { get; set; }
    public virtual DbSet<LogonRecord> LogonRecord { get; set; }
    public virtual DbSet<MailList> MailList { get; set; }
    public virtual DbSet<ManagementOfAgriculturalEnterprises> ManagementOfAgriculturalEnterprises { get; set; }
    public virtual DbSet<ManagementOfLargeHouseholds> ManagementOfLargeHouseholds { get; set; }
    public virtual DbSet<ManagementOfOrdinaryPeasantHouseholds> ManagementOfOrdinaryPeasantHouseholds { get; set; }
    public virtual DbSet<ManagementOfOutstandingPartyMembers> ManagementOfOutstandingPartyMembers { get; set; }
    public virtual DbSet<ManagementOfPartyBuildingActivities> ManagementOfPartyBuildingActivities { get; set; }
    public virtual DbSet<ManagementOfQuarterlyAssessmentWork> ManagementOfQuarterlyAssessmentWork { get; set; }
    public virtual DbSet<ManagementOfUrban> ManagementOfUrban { get; set; }
    public virtual DbSet<ManagementOfUrbanPersonnel> ManagementOfUrbanPersonnel { get; set; }
    public virtual DbSet<Meeting> Meeting { get; set; }
    public virtual DbSet<MembershipDuesPaymentManagement> MembershipDuesPaymentManagement { get; set; }
    public virtual DbSet<MenuConfiguration> MenuConfiguration { get; set; }
    public virtual DbSet<Militia> Militia { get; set; }
    public virtual DbSet<MonitoringList> MonitoringList { get; set; }
    public virtual DbSet<MonthlyListManagement> MonthlyListManagement { get; set; }
    public virtual DbSet<MyActivities> MyActivities { get; set; }
    public virtual DbSet<MyHandPat> MyHandPat { get; set; }
    public virtual DbSet<MyReservation> MyReservation { get; set; }
    public virtual DbSet<MySuggestion> MySuggestion { get; set; }
    public virtual DbSet<NameOfTheNewborn> NameOfTheNewborn { get; set; }
    public virtual DbSet<Newborn> Newborn { get; set; }
    public virtual DbSet<Notice> Notice { get; set; }
    public virtual DbSet<NoticeBulletin> NoticeBulletin { get; set; }
    public virtual DbSet<NoticeReadingRecord> NoticeReadingRecord { get; set; }
    public virtual DbSet<OrganizationalManagement> OrganizationalManagement { get; set; }
    public virtual DbSet<OrganizationalStructure> OrganizationalStructure { get; set; }
    public virtual DbSet<OutstandingPartyMembers> OutstandingPartyMembers { get; set; }
    public virtual DbSet<ParkEngineeringManagement> ParkEngineeringManagement { get; set; }
    public virtual DbSet<PartyBranchManagement> PartyBranchManagement { get; set; }
    public virtual DbSet<PartyBuilding> PartyBuilding { get; set; }
    public virtual DbSet<PartyBuildingProject> PartyBuildingProject { get; set; }
    public virtual DbSet<PartyNewsManagement> PartyNewsManagement { get; set; }
    public virtual DbSet<Pat> Pat { get; set; }
    public virtual DbSet<PermissionSynchronization> PermissionSynchronization { get; set; }
    public virtual DbSet<PersonalInformation> PersonalInformation { get; set; }
    public virtual DbSet<PhotographyWorld> PhotographyWorld { get; set; }
    public virtual DbSet<POI> POI { get; set; }
    public virtual DbSet<PolicyDocument> PolicyDocument { get; set; }
    public virtual DbSet<Population> Population { get; set; }
    public virtual DbSet<ProjectManagement> ProjectManagement { get; set; }
    public virtual DbSet<ProjectManagementOfParkEngineering> ProjectManagementOfParkEngineering { get; set; }
    public virtual DbSet<ProjectProgress> ProjectProgress { get; set; }
    public virtual DbSet<RecommendedTreatment> RecommendedTreatment { get; set; }
    public virtual DbSet<RecordingLectures> RecordingLectures { get; set; }
    public virtual DbSet<RecordOfElectricityPayment> RecordOfElectricityPayment { get; set; }
    public virtual DbSet<RecordOfPartyClass> RecordOfPartyClass { get; set; }
    public virtual DbSet<RecordOfRentCollection> RecordOfRentCollection { get; set; }
    public virtual DbSet<ReimbursementList> ReimbursementList { get; set; }
    public virtual DbSet<RentRecord> RentRecord { get; set; }
    public virtual DbSet<ReportOnTheProject> ReportOnTheProject { get; set; }
    public virtual DbSet<ResidentPopulationManagement> ResidentPopulationManagement { get; set; }
    public virtual DbSet<RoleConfiguration> RoleConfiguration { get; set; }
    public virtual DbSet<RoleMenu> RoleMenu { get; set; }
    public virtual DbSet<RunBusiness> RunBusiness { get; set; }
    public virtual DbSet<RuralMedicalTreatment> RuralMedicalTreatment { get; set; }
    public virtual DbSet<SanitationActivities> SanitationActivities { get; set; }
    public virtual DbSet<SanitationPersonnel> SanitationPersonnel { get; set; }
    public virtual DbSet<SanitationPersonnelManagement> SanitationPersonnelManagement { get; set; }
    public virtual DbSet<SanitationProblem> SanitationProblem { get; set; }
    public virtual DbSet<SanitationProblemManagement> SanitationProblemManagement { get; set; }
    public virtual DbSet<ScheduleManagement> ScheduleManagement { get; set; }
    public virtual DbSet<ScheduleWork> ScheduleWork { get; set; }
    public virtual DbSet<SecurityManagement> SecurityManagement { get; set; }
    public virtual DbSet<SecurityPatrolRecord> SecurityPatrolRecord { get; set; }
    public virtual DbSet<Service> Service { get; set; }
    public virtual DbSet<ServiceReservation> ServiceReservation { get; set; }
    public virtual DbSet<Shareholders> Shareholders { get; set; }
    public virtual DbSet<Sneakers> Sneakers { get; set; }
    public virtual DbSet<SocialConditionsAndPublicOpinions> SocialConditionsAndPublicOpinions { get; set; }
    public virtual DbSet<SocialSecurityManagement> SocialSecurityManagement { get; set; }
    public virtual DbSet<SpecialCrowdManagement> SpecialCrowdManagement { get; set; }
    public virtual DbSet<SpecialWork> SpecialWork { get; set; }
    public virtual DbSet<Suggestion> Suggestion { get; set; }
    public virtual DbSet<SuggestionRecord> SuggestionRecord { get; set; }
    public virtual DbSet<Supervision> Supervision { get; set; }
    public virtual DbSet<SupervisoryResponsibilityListManagement> SupervisoryResponsibilityListManagement { get; set; }
    public virtual DbSet<SYS_Code> SYS_Code { get; set; }
    public virtual DbSet<SystemConfiguration> SystemConfiguration { get; set; }
    public virtual DbSet<SystemLog> SystemLog { get; set; }
    public virtual DbSet<TalentManagement> TalentManagement { get; set; }
    public virtual DbSet<TheObjectOfCare> TheObjectOfCare { get; set; }
    public virtual DbSet<ThePartyStyleAndCleanGovernment> ThePartyStyleAndCleanGovernment { get; set; }
    public virtual DbSet<TheRoadGuardLine> TheRoadGuardLine { get; set; }
    public virtual DbSet<TheStudyOfPartyStyleAndCleanGovernment> TheStudyOfPartyStyleAndCleanGovernment { get; set; }
    public virtual DbSet<ThreeProductionBuilding> ThreeProductionBuilding { get; set; }
    public virtual DbSet<ToDoBusiness> ToDoBusiness { get; set; }
    public virtual DbSet<TouristInformation> TouristInformation { get; set; }
    public virtual DbSet<TouristInformationManagement> TouristInformationManagement { get; set; }
    public virtual DbSet<Traffic> Traffic { get; set; }
    public virtual DbSet<TrafficControl> TrafficControl { get; set; }
    public virtual DbSet<TwoTypesOfOrganizations> TwoTypesOfOrganizations { get; set; }
    public virtual DbSet<UnitDepartmentManagement> UnitDepartmentManagement { get; set; }
    public virtual DbSet<UrbanManagementActivities> UrbanManagementActivities { get; set; }
    public virtual DbSet<UserInformation> UserInformation { get; set; }
    public virtual DbSet<UserMenu> UserMenu { get; set; }
    public virtual DbSet<UserMessageQueue> UserMessageQueue { get; set; }
    public virtual DbSet<UserRole> UserRole { get; set; }
    public virtual DbSet<VideoPointBitInformation> VideoPointBitInformation { get; set; }
    public virtual DbSet<VillageHistory> VillageHistory { get; set; }
    public virtual DbSet<WaterLevelDetection> WaterLevelDetection { get; set; }
    public virtual DbSet<WelfareGrant> WelfareGrant { get; set; }
    public virtual DbSet<WorkLog> WorkLog { get; set; }
    public virtual DbSet<Workshop> Workshop { get; set; }

    public virtual int AddComments(string table, string column, string comments)
    {
        var tableParameter = table != null ?
            new ObjectParameter("table", table) :
            new ObjectParameter("table", typeof(string));

        var columnParameter = column != null ?
            new ObjectParameter("column", column) :
            new ObjectParameter("column", typeof(string));

        var commentsParameter = comments != null ?
            new ObjectParameter("comments", comments) :
            new ObjectParameter("comments", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddComments", tableParameter, columnParameter, commentsParameter);
    }

    public virtual int SP_GET_ALL_LIST(string districtID, string type, string condition, string search, string view, string order, string asc, Nullable<int> offset, Nullable<int> limit, ObjectParameter total)
    {
        var districtIDParameter = districtID != null ?
            new ObjectParameter("districtID", districtID) :
            new ObjectParameter("districtID", typeof(string));

        var typeParameter = type != null ?
            new ObjectParameter("type", type) :
            new ObjectParameter("type", typeof(string));

        var conditionParameter = condition != null ?
            new ObjectParameter("condition", condition) :
            new ObjectParameter("condition", typeof(string));

        var searchParameter = search != null ?
            new ObjectParameter("search", search) :
            new ObjectParameter("search", typeof(string));

        var viewParameter = view != null ?
            new ObjectParameter("view", view) :
            new ObjectParameter("view", typeof(string));

        var orderParameter = order != null ?
            new ObjectParameter("order", order) :
            new ObjectParameter("order", typeof(string));

        var ascParameter = asc != null ?
            new ObjectParameter("asc", asc) :
            new ObjectParameter("asc", typeof(string));

        var offsetParameter = offset.HasValue ?
            new ObjectParameter("offset", offset) :
            new ObjectParameter("offset", typeof(int));

        var limitParameter = limit.HasValue ?
            new ObjectParameter("limit", limit) :
            new ObjectParameter("limit", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_ALL_LIST", districtIDParameter, typeParameter, conditionParameter, searchParameter, viewParameter, orderParameter, ascParameter, offsetParameter, limitParameter, total);
    }
}
