//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Workshop
{
    public string id { get; set; }
    public string WIndustrialPark { get; set; }
    public string W { get; set; }
    public Nullable<float> WAreaCovered { get; set; }
    public Nullable<float> WTotalArea { get; set; }
    public Nullable<System.DateTime> WContractDate { get; set; }
    public string WRent { get; set; }
    public string WEnterpriseName { get; set; }
    public string WEnterpriseLeader { get; set; }
    public string WEnterpriseLeaderPhone { get; set; }
    public string WEnterpriseAddress { get; set; }
    public string WProductionType { get; set; }
    public string WUploadEnvironmentalProtectionFormalities { get; set; }
    public string WOccupationalHazards { get; set; }
    public string WHeadOfTheIndustrialPark { get; set; }
    public Nullable<int> VersionNo { get; set; }
    public string TransactionID { get; set; }
    public string CreateBy { get; set; }
    public Nullable<System.DateTime> CreateOn { get; set; }
    public string UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateOn { get; set; }
    public string DataLevel { get; set; }
    public string Latitude { get; set; }
    public string Longitude { get; set; }
    public Nullable<int> IsDeleted { get; set; }
    public Nullable<int> ord { get; set; }
    public string Polyline { get; set; }
    public string Polygon { get; set; }
}
