export default {
    "MenuConfiguration": {
        "debug": null,
        "Columns": [{
            "column_name": "MCCaption",
            "column_description": "标题",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "Caption"
        }, {
            "column_name": "MCParentTitle",
            "column_description": "父级标题",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "ParentTitle"
        }, {
            "column_name": "MCLink",
            "column_description": "链接",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "Link"
        }, {
            "column_name": "MCMenuType",
            "column_description": "菜单类型",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "MenuType"
        }, {
            "column_name": "MCSequence",
            "column_description": "顺序",
            "dbtype": "INT",
            "max_length": 0,
            "pascal_column_name": "Sequence"
        }, {
            "column_name": "MCDisplayName",
            "column_description": "显示名称",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "DisplayName"
        }, {
            "column_name": "MCPicture",
            "column_description": "图片",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "Picture"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "MenuConfiguration",
        "table_name_en": "MenuConfiguration",
        "table_name_ch": "菜单配置",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "RoleMenu": {
        "debug": null,
        "Columns": [{
            "column_name": "RMRoleName",
            "column_description": "角色名称",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "RoleName"
        }, {
            "column_name": "RMMenuTitle",
            "column_description": "菜单标题",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "MenuTitle"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "RoleMenu",
        "table_name_en": "RoleMenu",
        "table_name_ch": "角色菜单",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "UserRole": {
        "debug": null,
        "Columns": [{
            "column_name": "URRoleName",
            "column_description": "角色名称",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "RoleName"
        }, {
            "column_name": "URLoginName",
            "column_description": "登录名",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "LoginName"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "UserRole",
        "table_name_en": "UserRole",
        "table_name_ch": "用户角色",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "RoleConfiguration": {
        "debug": null,
        "Columns": [{
            "column_name": "RCRoleName",
            "column_description": "角色名称",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "RoleName"
        }, {
            "column_name": "RCAffiliatedOrganization",
            "column_description": "所属组织",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "AffiliatedOrganization"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "RoleConfiguration",
        "table_name_en": "RoleConfiguration",
        "table_name_ch": "角色配置",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "UserInformation": {
        "debug": null,
        "Columns": [{
            "column_name": "UIJobNumber",
            "column_description": "工号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "JobNumber"
        }, {
            "column_name": "UILoginName",
            "column_description": "登录名",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "LoginName"
        }, {
            "column_name": "UINickname",
            "column_description": "昵称",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Nickname"
        }, {
            "column_name": "UIRealName",
            "column_description": "真实姓名",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "RealName"
        }, {
            "column_name": "UIHeadPortrait",
            "column_description": "头像",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "HeadPortrait"
        }, {
            "column_name": "UIDepartment",
            "column_description": "部门",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Department"
        }, {
            "column_name": "UIPost",
            "column_description": "职位",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Post"
        }, {
            "column_name": "UIBooth",
            "column_description": "电话",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Booth"
        }, {
            "column_name": "UIPhoto",
            "column_description": "照片",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "Photo"
        }, {
            "column_name": "UICustomerType",
            "column_description": "用户类型",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "CustomerType"
        }, {
            "column_name": "UIUserLevel",
            "column_description": "用户级别",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "UserLevel"
        }, {
            "column_name": "UITimeOfEntry",
            "column_description": "入职时间",
            "dbtype": "DATETIME",
            "max_length": 0,
            "pascal_column_name": "TimeOfEntry"
        }, {
            "column_name": "UIDepartureTime",
            "column_description": "离职时间",
            "dbtype": "DATETIME",
            "max_length": 0,
            "pascal_column_name": "DepartureTime"
        }, {
            "column_name": "UICode",
            "column_description": "密码",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Code"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "UserInformation",
        "table_name_en": "UserInformation",
        "table_name_ch": "用户信息",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "LogonRecord": {
        "debug": null,
        "Columns": [{
            "column_name": "LRLoginName",
            "column_description": "登录名",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "LoginName"
        }, {
            "column_name": "LRLoginTime",
            "column_description": "登录时间",
            "dbtype": "DATETIME",
            "max_length": 0,
            "pascal_column_name": "LoginTime"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "LogonRecord",
        "table_name_en": "LogonRecord",
        "table_name_ch": "登录记录",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "UserMenu": {
        "debug": null,
        "Columns": [{
            "column_name": "UMLoginName",
            "column_description": "登录名",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "LoginName"
        }, {
            "column_name": "UMCaption",
            "column_description": "标题",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "Caption"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "UserMenu",
        "table_name_en": "UserMenu",
        "table_name_ch": "用户菜单",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "SystemConfiguration": {
        "debug": null,
        "Columns": [{
            "column_name": "SCKey",
            "column_description": "键",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Key"
        }, {
            "column_name": "SCAccrued",
            "column_description": "值",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Accrued"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "SystemConfiguration",
        "table_name_en": "SystemConfiguration",
        "table_name_ch": "系统配置",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "Customertype": {
        "debug": null,
        "Columns": [{
            "column_name": "CCustomerNumber",
            "column_description": "客户编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "CustomerNumber"
        }, {
            "column_name": "CName",
            "column_description": "姓名",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Name"
        }, {
            "column_name": "CChairperson",
            "column_description": "性别",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Chairperson"
        }, {
            "column_name": "CCall",
            "column_description": "称呼",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Call"
        }, {
            "column_name": "CCommonModeOfContact",
            "column_description": "联系方式",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "CommonModeOfContact"
        }, {
            "column_name": "CAddress",
            "column_description": "地址",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "Address"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "Customertype",
        "table_name_en": "Customertype",
        "table_name_ch": "客户",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "Supplier": {
        "debug": null,
        "Columns": [{
            "column_name": "SSupplierNumber",
            "column_description": "供应商编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "SupplierNumber"
        }, {
            "column_name": "SSupplierName",
            "column_description": "供应商名称",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "SupplierName"
        }, {
            "column_name": "SCommonModeOfContact",
            "column_description": "联系方式",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "CommonModeOfContact"
        }, {
            "column_name": "SOfficeLocation",
            "column_description": "办公地点",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "OfficeLocation"
        }, {
            "column_name": "SScopeOfOperation",
            "column_description": "经营范围",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "ScopeOfOperation"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "Supplier",
        "table_name_en": "Supplier",
        "table_name_ch": "供应商",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "TypeOfGoods": {
        "debug": null,
        "Columns": [{
            "column_name": "TOGCategoryNumberOfGoods",
            "column_description": "货品种类编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "CategoryNumberOfGoods"
        }, {
            "column_name": "TOGNameOfGoods",
            "column_description": "货物名称",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "NameOfGoods"
        }, {
            "column_name": "TOGCategoryOfGoods",
            "column_description": "货物类别",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "CategoryOfGoods"
        }, {
            "column_name": "TOGCargoSubcategory",
            "column_description": "货物子类别",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "CargoSubcategory"
        }, {
            "column_name": "TOGBulk",
            "column_description": "体积",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Bulk"
        }, {
            "column_name": "TOGColor",
            "column_description": "颜色",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Color"
        }, {
            "column_name": "TOGModel",
            "column_description": "型号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Model"
        }, {
            "column_name": "TOGAlias",
            "column_description": "别称",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Alias"
        }, {
            "column_name": "TOGPurchaseUnitPrice",
            "column_description": "采购单价",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "PurchaseUnitPrice"
        }, {
            "column_name": "TOGSalesUnitPrice",
            "column_description": "销售单价",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "SalesUnitPrice"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "TypeOfGoods",
        "table_name_en": "TypeOfGoods",
        "table_name_ch": "货物种类",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "SupplyChannel": {
        "debug": null,
        "Columns": [{
            "column_name": "SCSupplier",
            "column_description": "供应商",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Supplier"
        }, {
            "column_name": "SCTypeOfGoods",
            "column_description": "货物种类",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "TypeOfGoods"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "SupplyChannel",
        "table_name_en": "SupplyChannel",
        "table_name_ch": "供货渠道",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "Order": {
        "debug": null,
        "Columns": [{
            "column_name": "OOrderNumber",
            "column_description": "订单编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "OrderNumber"
        }, {
            "column_name": "OSupplierNumber",
            "column_description": "供应商编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "SupplierNumber"
        }, {
            "column_name": "OExpectedArrivalDate",
            "column_description": "期望到达日期",
            "dbtype": "DATETIME",
            "max_length": 0,
            "pascal_column_name": "ExpectedArrivalDate"
        }, {
            "column_name": "ODateOfSubmission",
            "column_description": "提交日期",
            "dbtype": "DATETIME",
            "max_length": 0,
            "pascal_column_name": "DateOfSubmission"
        }, {
            "column_name": "OSubmitter",
            "column_description": "提交人",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Submitter"
        }, {
            "column_name": "OAuthorsContactInformation",
            "column_description": "提交人联系方式",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "AuthorsContactInformation"
        }, {
            "column_name": "OOrderStatus",
            "column_description": "订单状态",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "OrderStatus"
        }, {
            "column_name": "ORemarks",
            "column_description": "备注",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "Remarks"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "Order",
        "table_name_en": "Order",
        "table_name_ch": "订单",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "OrderDetails": {
        "debug": null,
        "Columns": [{
            "column_name": "ODOrderNumber",
            "column_description": "订单编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "OrderNumber"
        }, {
            "column_name": "ODTypeOfGoods",
            "column_description": "货物种类",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "TypeOfGoods"
        }, {
            "column_name": "ODQuantityOfGoods",
            "column_description": "货物数量",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "QuantityOfGoods"
        }, {
            "column_name": "ODPurchaseUnitPrice",
            "column_description": "采购单价",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "PurchaseUnitPrice"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "OrderDetails",
        "table_name_en": "OrderDetails",
        "table_name_ch": "订单明细",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "WarehousingRecord": {
        "debug": null,
        "Columns": [{
            "column_name": "WROrderNumber",
            "column_description": "订单编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "OrderNumber"
        }, {
            "column_name": "WRDateOfArrival",
            "column_description": "到货日期",
            "dbtype": "DATETIME",
            "max_length": 0,
            "pascal_column_name": "DateOfArrival"
        }, {
            "column_name": "WRAgent",
            "column_description": "经办人",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Agent"
        }, {
            "column_name": "WROperatorContact",
            "column_description": "经办人联系方式",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "OperatorContact"
        }, {
            "column_name": "WRRemarks",
            "column_description": "备注",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "Remarks"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "WarehousingRecord",
        "table_name_en": "WarehousingRecord",
        "table_name_ch": "入库记录",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "Warehouse": {
        "debug": null,
        "Columns": [{
            "column_name": "WWarehouseNumber",
            "column_description": "仓库编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "WarehouseNumber"
        }, {
            "column_name": "WCapacity",
            "column_description": "容积",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Capacity"
        }, {
            "column_name": "WLocation",
            "column_description": "位置",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Location"
        }, {
            "column_name": "WResponsibleForManualNumber",
            "column_description": "负责人工号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "ResponsibleForManualNumber"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "Warehouse",
        "table_name_en": "Warehouse",
        "table_name_ch": "仓库",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "GoodsShelves": {
        "debug": null,
        "Columns": [{
            "column_name": "GSShelfNumber",
            "column_description": "货架编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "ShelfNumber"
        }, {
            "column_name": "GSVolume",
            "column_description": "容积 ",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Volume"
        }, {
            "column_name": "GSLocation",
            "column_description": "位置",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Location"
        }, {
            "column_name": "GSResponsibleForManualNumber",
            "column_description": "负责人工号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "ResponsibleForManualNumber"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "GoodsShelves",
        "table_name_en": "GoodsShelves",
        "table_name_ch": "货架",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "ReplenishmentApplicationForm": {
        "debug": null,
        "Columns": [{
            "column_name": "RAFApplicationNumber",
            "column_description": "申请单编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "ApplicationNumber"
        }, {
            "column_name": "RAFShelfNumber",
            "column_description": "货架编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "ShelfNumber"
        }, {
            "column_name": "RAFWarehouseNumber",
            "column_description": "仓库编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "WarehouseNumber"
        }, {
            "column_name": "RAFApplicationManualNumber",
            "column_description": "申请人工号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "ApplicationManualNumber"
        }, {
            "column_name": "RAFCategoryNumberOfGoods",
            "column_description": "货品种类编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "CategoryNumberOfGoods"
        }, {
            "column_name": "RAFQuantityOfGoods",
            "column_description": "货品数量",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "QuantityOfGoods"
        }, {
            "column_name": "RAFApplicationDate",
            "column_description": "申请日期",
            "dbtype": "DATETIME",
            "max_length": 0,
            "pascal_column_name": "ApplicationDate"
        }, {
            "column_name": "RAFApplicationStatus",
            "column_description": "申请单状态",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "ApplicationStatus"
        }, {
            "column_name": "RAFRemarks",
            "column_description": "备注",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "Remarks"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "ReplenishmentApplicationForm",
        "table_name_en": "ReplenishmentApplicationForm",
        "table_name_ch": "补货申请单",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "ReplenishmentRecord": {
        "debug": null,
        "Columns": [{
            "column_name": "RRApplicationNumber",
            "column_description": "申请单编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "ApplicationNumber"
        }, {
            "column_name": "RRDateOfArrival",
            "column_description": "到货日期",
            "dbtype": "DATETIME",
            "max_length": 0,
            "pascal_column_name": "DateOfArrival"
        }, {
            "column_name": "RRRemarks",
            "column_description": "备注",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "Remarks"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "ReplenishmentRecord",
        "table_name_en": "ReplenishmentRecord",
        "table_name_ch": "补货记录",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    },
    "SalesRecord": {
        "debug": null,
        "Columns": [{
            "column_name": "SRSalesLotNumber",
            "column_description": "销售批次号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "SalesLotNumber"
        }, {
            "column_name": "SRTypeOfGoods",
            "column_description": "货物种类",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "TypeOfGoods"
        }, {
            "column_name": "SRAmount",
            "column_description": "数量",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "Amount"
        }, {
            "column_name": "SRUnitPrice",
            "column_description": "单价",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "UnitPrice"
        }, {
            "column_name": "SRSalesNumber",
            "column_description": "销售工号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "SalesNumber"
        }, {
            "column_name": "SRInvoiceNumber",
            "column_description": "发票编号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "InvoiceNumber"
        }, {
            "column_name": "SRInvoicesAreRaised",
            "column_description": "发票抬头",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "InvoicesAreRaised"
        }, {
            "column_name": "SRDutyParagraph",
            "column_description": "税号",
            "dbtype": "NVARCHAR(50)",
            "max_length": 0,
            "pascal_column_name": "DutyParagraph"
        }, {
            "column_name": "SRRemarks",
            "column_description": "备注",
            "dbtype": "NVARCHAR(4000)",
            "max_length": 0,
            "pascal_column_name": "Remarks"
        }],
        "Children": null,
        "Parent": null,
        "r": null,
        "table_name": "SalesRecord",
        "table_name_en": "SalesRecord",
        "table_name_ch": "销售记录",
        "column_name": null,
        "column_description": null,
        "dbtype": null,
        "max_length": 0
    }
}